// Generated by scripts/rig-uni.py — do not edit by hand.
// Rig bound with computed weights from public/models/uni/uni.glb.

/** Metres Uni's body advances over one full cycle of the baked walk clip. */
export const UNI_STRIDE_METRES = 0.6683;

/** Seconds of one full cycle of the baked walk clip. */
export const UNI_WALK_CYCLE_SECONDS = 1.0000;
