// Generated by scripts/rig-uni.py from assets/models/uni/uni.glb — do not edit by hand.

/** Metres Uni's body advances over one full cycle of the baked walk clip. */
export const UNI_STRIDE_METRES = 0.6683;
